### ISSUE TITLE
NoMethodError: undefined method `[]' for #<SOAP::Mapping::SchemaSequenceDefinition>

### ISSUE THREAD

**Issue by rubyjedi** [rubyjedi/soap4r#1]
NoMethodError: undefined method `[]' for #<SOAP::Mapping::SchemaSequenceDefinition:0x7f794f030a50>
    /home/lalee/research/Soap4R.up/lib/soap/mapping/encodedregistry.rb:441:in`array2soap'
    /home/lalee/research/Soap4R.up/lib/soap/mapping/encodedregistry.rb:429:in `stubobj2soap'
    /home/lalee/research/Soap4R.up/lib/soap/mapping/encodedregistry.rb:342:in`_obj2soap'
    /home/lalee/research/Soap4R.up/lib/soap/mapping/encodedregistry.rb:301:in `obj2soap'
    /home/lalee/research/Soap4R.up/lib/soap/mapping/mapping.rb:135:in`_obj2soap'
    /home/lalee/research/Soap4R.up/lib/soap/mapping/mapping.rb:43:in `obj2soap'
    /home/lalee/research/Soap4R.up/lib/soap/mapping/mapping.rb:559:in`protect_mapping'
    /home/lalee/research/Soap4R.up/lib/soap/mapping/mapping.rb:532:in `protect_threadvars'
    /home/lalee/research/Soap4R.up/lib/soap/mapping/mapping.rb:548:in`protect_mapping'
    /home/lalee/research/Soap4R.up/lib/soap/mapping/mapping.rb:42:in `obj2soap'
    /home/lalee/research/Soap4R.up/lib/soap/marshal.rb:38:in`marshal'

**Comment by godgav** [comment]
to fix this you need to define

`def [ ](index) @content[index] end`

in schemadefinition.rb inside SchemaComplexTypeDefinition module. Hope this will help to somebody

**Comment by rubyjedi** [comment]
I'm closing this one as stale. If you're still facing this issue, please let me know and we can discuss/reopen if necessary. Thanks.
