### ISSUE TITLE
TLS version supported

### ISSUE THREAD

**Issue by ilavenilp** [rubyjedi/soap4r#17]
I would like to know what is the current versions of SSL & TLS supported by soap4r (1.5.8).

Basically I am using Soap4R as SOAP Webservice Client which is using httpclient under the hood. I need to ensure that my app supports TLS1.2+ protocol. 

Please help.
thanks
Sateesh

**Comment by rubyjedi** [comment]
Just to clear up any confusion:  Soap4R 1.5.8 is the upstream branch:  https://github.com/nahi/soap4r .  This is an independent fork of Soap4R, and is Version 2.0.3.

As Soap4R uses httpclient, any and all support for SSL or TLS falls upon how (and what version of) httpclient and OpenSSL are compiled.

If you need to use specific SSL protocols, you will need to set the options to the SOAP driver (client) accordingly.
