### ISSUE TITLE
Quotes and forward slashes getting escaped when making soap call

### ISSUE THREAD

**Issue by aaronapayne** [rubyjedi/soap4r#2]
I am making a soap call that contains a single quote.  When the call gets made, the single quote seems to be getting escaped and it is posting \' instead.  The same goes for backslash.  Any chance you could look into this?

Thanks!

**Comment by rubyjedi** [comment]
I'll have a look into this next week, and see if anything can be done.

Just to confirm (so I can make a test case)... You're just passing a string message, and these messages are escaping backslashes and single quotes?  Odd that this wasn't caught sooner...

**Comment by aaronapayne** [comment]
I'm not positive about back slashes, but yes, this is what is happening with single and double quotes.

**Comment by rubyjedi** [comment]
Note: There were issues regarding RegEx encodings; and there was also a Regex mask related to quotes that somehow got corrupted.

I'm closing this one as stale. If you're still facing this issue after my upcoming code push (within the week), please let me know and we can discuss/reopen if necessary. Thanks.
