### ISSUE TITLE
International UTF-8 character strings issue with older version of httpclient

### ISSUE THREAD

**Issue by nlloyd** [rubyjedi/soap4r#5]
I am working with japanese characters in the XML being generated through this library.  The problem is that there is a distinct difference between String.size and String.bytesize when handling the generated XML.

The current httpclient does a check if which the version required in soap4r does not, which is if bytesize exists as a function for the provided HTTP request body.

Can you please update the version of httpclient in the gemspec for the next release?

**Comment by rubyjedi** [comment]
Upcoming code push is geared toward HTTPClient 2.6 and higher.

I'm closing this one as stale. If you're still facing this issue after my upcoming code push (within the week), please let me know and we can discuss/reopen if necessary. Thanks.
